export enum InvoiceListColumns {
  order = 'order',
  orderProductId = 'orderProductId',
  delivery = 'delivery',
  invoice = 'invoice',
  documentNo = 'documentNo',
  customStatus = 'customStatus',
  buyer = 'buyer',
  supplier = 'supplier',
  vessel = 'vessel',
  carrierCompany = 'carrierCompany',
  paymentCompany = 'paymentCompany',
  agreementType = 'agreementType',
  port = 'port',
  eta = 'eta',
  deliveryDate = 'deliveryDate',
  line = 'line',
  product = 'product',
  invoiceQuantity = 'invoiceQuantity',
  price = 'price',
  sumOfCosts = 'sumOfCosts',
  invoiceAmount = 'invoiceAmount',
  confirmedQuantity = 'confirmedQuantity',
  orderPrice = 'orderPrice',
  orderAmount = 'orderAmount',
  invoiceStatus = 'invoiceStatus',
  dueDate = 'dueDate',
  workingDueDate = 'workingDueDate',
  paymentDate = 'paymentDate',
  receivedDate = 'receivedDate',
  approvedDate = 'approvedDate',
  backOfficeComments = 'backOfficeComments',
  orderStatus = 'orderStatus',
  productType = 'productType',
  invoiceApprovalStatus = 'invoiceApprovalStatus'
}

export enum InvoiceListColumnsLabels {
  order = 'Order No',
  orderProductId = 'Order Product ID',
  delivery = 'Delivery No',
  invoice = 'Invoice No',
  documentNo = 'Document No',
  customStatus = 'Invoice Status',
  buyer = 'Buyer',
  supplier = 'Seller',
  vessel = 'Vessel',
  carrierCompany = 'Carrier',
  paymentCompany = 'Payment Company',
  agreementType = 'Agreement Type',
  port = 'Port Name',
  eta = 'ETA',
  deliveryDate = 'Date of delivery',
  line = 'Service',
  product = 'Product',
  invoiceQuantity = 'Inv. Qty',
  price = 'Inv. Price',
  sumOfCosts = 'Invoice Cost',
  invoiceAmount = 'Invoice Amount',
  confirmedQuantity = 'Con Qty',
  orderPrice = 'Order Price',
  orderAmount = 'Order Amount',
  invoiceStatus = 'Invoice Approval Status',
  dueDate = 'Due Date',
  workingDueDate = 'Working Due Date',
  paymentDate = 'Payment Date',
  receivedDate = 'Invoice Received Date',
  approvedDate = 'Validation Date',
  backOfficeComments = 'Back Office Comments',
  orderStatus = 'Order Status',
  productType = 'Product Type',
  invoiceApprovalStatus = 'Recon Status'
}

export const InvoiceListColumnServerKeys: Record<InvoiceListColumns, string> = {
  [InvoiceListColumns.order]: 'order',
  [InvoiceListColumns.orderProductId]: 'orderProductId',
  [InvoiceListColumns.delivery]: 'delivery',
  [InvoiceListColumns.invoice]: 'invoice',
  [InvoiceListColumns.documentNo]: 'documentNo',
  [InvoiceListColumns.customStatus]: 'customStatus',
  [InvoiceListColumns.buyer]: 'buyer',
  [InvoiceListColumns.supplier]: 'supplier',
  [InvoiceListColumns.vessel]: 'vessel',
  [InvoiceListColumns.carrierCompany]: 'carrierCompany',
  [InvoiceListColumns.paymentCompany]: 'paymentCompany',
  [InvoiceListColumns.agreementType]: 'agreementType',
  [InvoiceListColumns.port]: 'port',
  [InvoiceListColumns.eta]: 'eta',
  [InvoiceListColumns.deliveryDate]: 'deliveryDate',
  [InvoiceListColumns.line]: 'line',
  [InvoiceListColumns.product]: 'product',
  [InvoiceListColumns.invoiceQuantity]: 'invoiceQuantity',
  [InvoiceListColumns.price]: 'price',
  [InvoiceListColumns.sumOfCosts]: 'sumOfCosts',
  [InvoiceListColumns.invoiceAmount]: 'invoiceAmount',
  [InvoiceListColumns.confirmedQuantity]: 'confirmedQuantity',
  [InvoiceListColumns.orderPrice]: 'orderPrice',
  [InvoiceListColumns.orderAmount]: 'orderAmount',
  [InvoiceListColumns.invoiceStatus]: 'invoiceStatus',
  [InvoiceListColumns.dueDate]: 'dueDate',
  [InvoiceListColumns.workingDueDate]: 'workingDueDate',
  [InvoiceListColumns.paymentDate]: 'paymentDate',
  [InvoiceListColumns.receivedDate]: 'receivedDate',
  [InvoiceListColumns.approvedDate]: 'approvedDate',
  [InvoiceListColumns.backOfficeComments]: 'backOfficeComments',
  [InvoiceListColumns.orderStatus]: 'orderStatus',
  [InvoiceListColumns.productType]: 'productType',
  [InvoiceListColumns.invoiceApprovalStatus]: 'invoiceApprovalStatus'
};
