export enum PaybleToListColumns {
  selection = 'selection',
  id = 'id',
  name = 'name',
  displayName = 'displayName',
  defaultPaymentTerm = 'defaultpaymentterm_name',
  parent = 'parent',
  isDeleted = 'isDeleted',
  reason = 'reason',
  status = 'status',
  comments = 'comments',
  defaultIncoterm = 'defaultIncoterm',
  supplier = 'supplier',
  seller = 'seller',
  broker = 'broker',
  customer = 'customer',
  agent = 'agent',
  surveyor = 'surveyor',
  barge = 'barge',
  lab = 'lab',
  planner = 'planner',
  internal = 'internal',
  sludge = 'sludge',
  country = 'country',
  createdBy = 'created_by',
  createdOn = 'createdOn',
  lastModifiedBy = 'last_modified_by',
  lastModifiedOn = 'lastModifiedOn',
  hasNoMoreChildren = 'has_no_more_children'
}

export enum PaybleToListColumnsLabels {
  id = 'Id',
  name = 'Counterparty',
  displayName = 'Display Name',
  defaultPaymentTerm = 'Default Payment Term',
  parent = 'Parent',
  isDeleted = 'Blacklisted',
  reason = 'Blacklisted Reason',
  status = 'Status',
  comments = 'Comments',
  defaultIncoterm = 'Default Inconterm',
  supplier = 'Supplier',
  seller = 'Seller',
  broker = 'Broker',
  customer = 'Customer',
  agent = 'Agent',
  surveyor = 'Surveyor',
  barge = 'Barge',
  lab = 'Lab',
  planner = 'Planner',
  internal = 'Internal',
  sludge = 'Sludge',
  country = 'Country',
  createdBy = 'Created By',
  createdOn = 'Created On',
  lastModifiedBy = 'Last Modified By',
  lastModifiedOn = 'Last Modified On',
  hasNoMoreChildren = 'Has No More Children'

}

export const PaybleToListColumnServerKeys: Record<
PaybleToListColumns,
  string
> = {
  [PaybleToListColumns.selection]: undefined,
  [PaybleToListColumns.id]: 'id',
  [PaybleToListColumns.name]: 'name',
  [PaybleToListColumns.displayName]: 'displayName',
  [PaybleToListColumns.defaultPaymentTerm]: 'defaultpaymentterm_name',
  [PaybleToListColumns.parent]: 'parent',
  [PaybleToListColumns.isDeleted]: 'isDeleted',
  [PaybleToListColumns.reason]: 'reason',
  [PaybleToListColumns.status]: 'status',
  [PaybleToListColumns.comments]: 'comments',
  [PaybleToListColumns.defaultIncoterm]: 'defaultIncoterm',
  [PaybleToListColumns.supplier]: 'supplier',
  [PaybleToListColumns.seller]: 'seller',
  [PaybleToListColumns.broker]: 'broker',
  [PaybleToListColumns.customer]: 'customer',
  [PaybleToListColumns.agent]: 'agent',
  [PaybleToListColumns.surveyor]: 'surveyor',
  [PaybleToListColumns.barge]: 'barge',
  [PaybleToListColumns.lab]: 'lab',
  [PaybleToListColumns.planner]: 'planner',
  [PaybleToListColumns.internal]: 'internal',
  [PaybleToListColumns.sludge]: 'sludge',
  [PaybleToListColumns.country]: 'country',
  [PaybleToListColumns.createdBy]: 'created_by',
  [PaybleToListColumns.createdOn]: 'createdOn',
  [PaybleToListColumns.lastModifiedBy]: 'last_modified_by',
  [PaybleToListColumns.lastModifiedOn]: 'lastModifiedOn',
  [PaybleToListColumns.hasNoMoreChildren]: 'has_no_more_children',

};
