export enum CustomerListColumns {
  selection = 'selection',
  id = 'id',
  name = 'name',
  displayName = 'displayName',
  defaultPaymentTerm = 'defaultpaymentterm_name',
  parent = 'parent',
  isDeleted = 'isDeleted',
  reason = 'reason',
  status = 'status',
  comments = 'comments',
  defaultIncoterm = 'defaultIncoterm',
  supplier = 'supplier',
  seller = 'seller',
  broker = 'broker',
  customer = 'customer',
  agent = 'agent',
  surveyor = 'surveyor',
  barge = 'barge',
  lab = 'lab',
  planner = 'planner',
  internal = 'internal',
  sludge = 'sludge',
  country = 'country',
  createdBy = 'created_by',
  createdOn = 'createdOn',
  lastModifiedBy = 'last_modified_by',
  lastModifiedOn = 'lastModifiedOn',
  hasNoMoreChildren = 'has_no_more_children'
}

export enum CustomerListColumnsLabels {
  id = 'Id',
  name = 'Name',
  displayName = 'Display Name',
  defaultPaymentTerm = 'Default Payment Term',
  parent = 'Parent',
  isDeleted = 'Blacklisted',
  reason = 'Blacklisted Reason',
  status = 'Status',
  comments = 'Comments',
  defaultIncoterm = 'Default Inconterm',
  supplier = 'Supplier',
  seller = 'Seller',
  broker = 'Broker',
  customer = 'Customer',
  agent = 'Agent',
  surveyor = 'Surveyor',
  barge = 'Barge',
  lab = 'Lab',
  planner = 'Planner',
  internal = 'Internal',
  sludge = 'Sludge',
  country = 'Country',
  createdBy = 'Created By',
  createdOn = 'Created On',
  lastModifiedBy = 'Last Modified By',
  lastModifiedOn = 'Last Modified On',
  hasNoMoreChildren = 'Has No More Children'

}

export const CustomerListColumnServerKeys: Record<
CustomerListColumns,
  string
> = {
  [CustomerListColumns.selection]: undefined,
  [CustomerListColumns.id]: 'id',
  [CustomerListColumns.name]: 'name',
  [CustomerListColumns.displayName]: 'displayName',
  [CustomerListColumns.defaultPaymentTerm]: 'defaultpaymentterm_name',
  [CustomerListColumns.parent]: 'parent',
  [CustomerListColumns.isDeleted]: 'isDeleted',
  [CustomerListColumns.reason]: 'reason',
  [CustomerListColumns.status]: 'status',
  [CustomerListColumns.comments]: 'comments',
  [CustomerListColumns.defaultIncoterm]: 'defaultIncoterm',
  [CustomerListColumns.supplier]: 'supplier',
  [CustomerListColumns.seller]: 'seller',
  [CustomerListColumns.broker]: 'broker',
  [CustomerListColumns.customer]: 'customer',
  [CustomerListColumns.agent]: 'agent',
  [CustomerListColumns.surveyor]: 'surveyor',
  [CustomerListColumns.barge]: 'barge',
  [CustomerListColumns.lab]: 'lab',
  [CustomerListColumns.planner]: 'planner',
  [CustomerListColumns.internal]: 'internal',
  [CustomerListColumns.sludge]: 'sludge',
  [CustomerListColumns.country]: 'country',
  [CustomerListColumns.createdBy]: 'created_by',
  [CustomerListColumns.createdOn]: 'createdOn',
  [CustomerListColumns.lastModifiedBy]: 'last_modified_by',
  [CustomerListColumns.lastModifiedOn]: 'lastModifiedOn',
  [CustomerListColumns.hasNoMoreChildren]: 'has_no_more_children',

};
