// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Shiptech.Negotiation.Domain.Data.Model
{
    public partial class Request
    {
        //public virtual List<RequestLocation> Locations { get; set; }
    }
}