{
    "Orders": {
        "columns": [{
            "caption": "",
            "alwaysVisible": true,
            "sortable": false,
            "sortableName": ""
        }, {
            "caption": "PAGES.ORDER_LIST.ORDER_ID",
            "visible": true,
            "sortable": true,
            "sortableName": "order_name",
            "dtoPath": "order.name"
        }, {
            "caption": "PAGES.ORDER_LIST.ORDER_ETA",
            "visible": true,
            "sortable": true,
            "sortableName": "Eta",
            "dtoPath": "eta",
            "type": "date"
        }, {
            "caption": "PAGES.ORDER_LIST.ORDER_DATE",
            "visible": true,
            "sortable": true,
            "sortableName": "OrderDate",
            "dtoPath": "orderDate",
            "type": "date"
        }, {
            "caption": "PAGES.ORDER_LIST.REQUEST_ID",
            "visible": true,
            "sortable": true,
            "sortableName": "request_id",
            "dtoPath": "request.id"
        }, {
            "caption": "PAGES.ORDER_LIST.SERVICE",
            "visible": true,
            "sortable": true,
            "sortableName": "service_name",
            "dtoPath": "service.name"
        }, {
            "caption": "PAGES.ORDER_LIST.SELLER",
            "visible": true,
            "sortable": true,
            "sortableName": "seller_name",
            "dtoPath": "seller.name"
        }, {
            "caption": "PAGES.ORDER_LIST.BUYER",
            "visible": true,
            "sortable": true,
            "sortableName": "buyer_name",
            "dtoPath": "buyer.name"
        }, {
            "caption": "PAGES.ORDER_LIST.VESSEL",
            "visible": true,
            "sortable": true,
            "sortableName": "vessel_name",
            "dtoPath": "vessel.name"
        }, {
            "caption": "PAGES.ORDER_LIST.IMO",
            "visible": true,
            "sortable": true,
            "sortableName": "vesselImoNo",
            "dtoPath": "vesselImoNo"
        }, {
            "caption": "PAGES.ORDER_LIST.LOCATION",
            "visible": true,
            "sortable": true,
            "sortableName": "location_name",
            "dtoPath": "location.name"
        }, {
            "caption": "PAGES.ORDER_LIST.PRODUCT",
            "visible": true,
            "sortable": true,
            "sortableName": "product_name",
            "dtoPath": "product.name"
        }, {
            "caption": "PAGES.ORDER_LIST.PRODUCT_STATUS",
            "visible": true,
            "sortable": true,
            "sortableName": "productStatus_name",
            "dtoPath": "productStatus.name"
        }, {
            "caption": "PAGES.ORDER_LIST.ORDER_STATUS",
            "visible": true,
            "sortable": true,
            "sortableName": "orderStatus_name",
            "dtoPath": "orderStatus.name"
        }, {
            "caption": "PAGES.ORDER_LIST.UNIT_PRICE_WITH_CURRENCY",
            "visible": false,
            "sortable": true,
            "sortableName": "Price,Currency_Name",
            "dtoPath": "Price,Currency_Name"
        }, {
            "caption": "PAGES.ORDER_LIST.CONFIRMED_QTY_WITH_UOM",
            "visible": false,
            "sortable": true,
            "sortableName": "ConfirmedQuantity,ConfirmedQuantityUom_Name",
            "dtoPath": "ConfirmedQuantity,ConfirmedQuantityUom_Name"
        }, {
            "caption": "PAGES.ORDER_LIST.AGREEMENT_TYPE",
            "visible": false,
            "sortable": true,
            "sortableName": "agreementType_name",
            "dtoPath": "agreementType.name"
        }, {
            "caption": "PAGES.ORDER_LIST.DELIVERY_OPTION",
            "visible": false,
            "sortable": true,
            "sortableName": "deliveryOption_name",
            "dtoPath": "deliveryOption.name"
        }, {
            "caption": "PAGES.ORDER_LIST.PHYSICAL_SUPPLIER",
            "visible": false,
            "sortable": true,
            "sortableName": "physicalSupplier_name",
            "dtoPath": "physicalSupplier.name"
        }, {
            "caption": "PAGES.ORDER_LIST.BROKER",
            "visible": false,
            "sortable": true,
            "sortableName": "broker_name",
            "dtoPath": "broker.name"
        }]
    }
}
