export enum QcDocumentsListColumns {
  selection = 'selection',
  portCallId = 'portCallId',
  portName = 'portName',
  vesselName = 'vesselName',
  surveyDate = 'surveyDate',
  surveyStatus = 'surveyStatus',
  qtyMatchedStatus = 'qtyMatchedStatus',
  logBookRobBeforeDelivery = 'logBookRobBeforeDelivery',
  measuredRobBeforeDelivery = 'measuredRobBeforeDelivery',
  diffRobBeforeDelivery = 'diffRobBeforeDelivery',
  qtyBeforeDeliveryUom = 'qtyBeforeDeliveryUom',
  bdnQuantity = 'bdnQuantity',
  measuredDeliveredQty = 'measuredDeliveredQty',
  diffDeliveredQty = 'diffDeliveredQty',
  qtyDeliveredUom = 'qtyDeliveredUom',
  logBookRobAfterDelivery = 'logBookRobAfterDelivery',
  measuredRobAfterDelivery = 'measuredRobAfterDelivery',
  diffRobAfterDelivery = 'diffRobAfterDelivery',
  qtyAfterDeliveryUom = 'qtyAfterDeliveryUom',
  logBookSludgeRobBeforeDischarge = 'logBookSludgeRobBeforeDischarge',
  measuredSludgeRobBeforeDischarge = 'measuredSludgeRobBeforeDischarge',
  diffSludgeRobBeforeDischarge = 'diffSludgeRobBeforeDischarge',
  sludgeDischargedQty = 'sludgeDischargedQty',
  qtySludgeDischargedUom = 'qtySludgeDischargedUom',
  comment = 'comment',
  isVerifiedSludgeQty = 'isVerifiedSludgeQty'
}

export enum QcDocumentsListColumnsLabels {
  portCallId = 'Call ID',
  portName = 'Port call',
  vesselName = 'Vessel',
  surveyDate = 'Survey Date',
  surveyStatus = 'Survey Status',
  qtyMatchedStatus = 'Qty Matched',
  logBookRobBeforeDelivery = 'Log Book ROB (before delivery) Qty',
  measuredRobBeforeDelivery = 'Measured ROB surveyor (before delivery) Qty',
  diffRobBeforeDelivery = 'ROB before the delivery diff',
  qtyBeforeDeliveryUom = 'Qty UOM',
  bdnQuantity = 'BDN Quantity (SUM)',
  measuredDeliveredQty = 'Measured Delivered Qty',
  diffDeliveredQty = 'Delivered Qty (diff)',
  qtyDeliveredUom = 'Qty UOM',
  logBookRobAfterDelivery = 'Log Book ROB (after delivery) Qty',
  measuredRobAfterDelivery = 'Measured ROB surveyor (after delivery) Qty',
  diffRobAfterDelivery = 'ROB after the delivery diff',
  qtyAfterDeliveryUom = 'Qty UOM',
  logBookSludgeRobBeforeDischarge = 'Log Book Sludge ROB (before discharge) Qty',
  measuredSludgeRobBeforeDischarge = 'Measured Sludge ROB Surveyor (before discharge) Qty',
  diffSludgeRobBeforeDischarge = 'ROB before discharge diff',
  sludgeDischargedQty = 'Discharged Qty',
  qtySludgeDischargedUom = 'Qty UOM',
  comment = 'Comment',
  isVerifiedSludgeQty = 'Verify Sludge Qty'
}

/**
 * The map serves the purposes of easily renaming columns on the front-end without affecting back-end filtering/sorting.
 */
export const QcDocumentsListColumnServerKeys: Record<QcDocumentsListColumns, string> = {
  [QcDocumentsListColumns.selection]: undefined,
  [QcDocumentsListColumns.portCallId]: 'portCallId',
  [QcDocumentsListColumns.portName]: 'portName',
  [QcDocumentsListColumns.vesselName]: 'vesselName',
  [QcDocumentsListColumns.surveyDate]: 'surveyDate',
  [QcDocumentsListColumns.surveyStatus]: 'SurveyStatus_DisplayName',
  [QcDocumentsListColumns.qtyMatchedStatus]: 'QtyMatchedStatus_DisplayName',
  [QcDocumentsListColumns.logBookRobBeforeDelivery]: 'logBookRobBeforeDelivery',
  [QcDocumentsListColumns.measuredRobBeforeDelivery]: 'measuredRobBeforeDelivery',
  [QcDocumentsListColumns.diffRobBeforeDelivery]: 'diffRobBeforeDelivery',
  [QcDocumentsListColumns.qtyBeforeDeliveryUom]: 'QtyBeforeDeliveryUom_Name',
  [QcDocumentsListColumns.bdnQuantity]: 'bdnQuantity',
  [QcDocumentsListColumns.measuredDeliveredQty]: 'measuredDeliveredQty',
  [QcDocumentsListColumns.diffDeliveredQty]: 'diffDeliveredQty',
  [QcDocumentsListColumns.qtyDeliveredUom]: 'QtyDeliveredUom_Name',
  [QcDocumentsListColumns.logBookRobAfterDelivery]: 'logBookRobAfterDelivery',
  [QcDocumentsListColumns.measuredRobAfterDelivery]: 'measuredRobAfterDelivery',
  [QcDocumentsListColumns.diffRobAfterDelivery]: 'diffRobAfterDelivery',
  [QcDocumentsListColumns.qtyAfterDeliveryUom]: 'QtyAfterDeliveryUom_Name',
  [QcDocumentsListColumns.logBookSludgeRobBeforeDischarge]: 'logBookSludgeRobBeforeDischarge',
  [QcDocumentsListColumns.measuredSludgeRobBeforeDischarge]: 'measuredSludgeRobBeforeDischarge',
  [QcDocumentsListColumns.diffSludgeRobBeforeDischarge]: 'diffSludgeRobBeforeDischarge',
  [QcDocumentsListColumns.sludgeDischargedQty]: 'sludgeDischargedQty',
  [QcDocumentsListColumns.qtySludgeDischargedUom]: 'QtySludgeDischargedUom_Name',
  [QcDocumentsListColumns.comment]: 'comment',
  [QcDocumentsListColumns.isVerifiedSludgeQty]: 'isVerifiedSludgeQty'
};
