export enum QcSoundingReportDetailsColumns {
  reportId = 'reportId',
  tankId = 'tankId',
  tankName = 'tankName',
  fuelDescription = 'fuelDescription',
  fuelVolume = 'fuelVolume',
  tankCapacity = 'tankCapacity',
  fuelTemp = 'fuelTemp',
  tankUnpumpableVolume = 'tankUnpumpableVolume',
  fuelMass = 'fuelMass',
}

export enum QcSoundingReportDetailsColumnsLabels {
  reportId = 'Report ID',
  tankId = 'Tank ID',
  tankName = 'Tank Name',
  fuelDescription = 'Fuel Desc',
  fuelVolume = 'Fuel volume',
  tankCapacity = 'Tank Capacity',
  fuelTemp = 'Fuel Temp',
  tankUnpumpableVolume = 'Tank Unpumpable Volume',
  fuelMass = 'Fuel Mass',
}

export enum QcSoundingReportListColumns {
  vesselName = 'vesselName',
  vesselCode = 'vesselCode',
  imoNo = 'imoNo',
  reportId = 'reportId',
  voyageReference = 'voyageReference',
  soundedOn = 'soundedOn',
  soundingReason = 'soundingReason',
  computedRobHsfo = 'computedRobHsfo',
  measuredRobHsfo = 'measuredRobHsfo',
  robHsfoDiff = 'robHsfoDiff',
  computedRobLsfo = 'computedRobLsfo',
  measuredRobLsfo = 'measuredRobLsfo',
  robLsfoDiff = 'robLsfoDiff',
  computedRobDogo = 'computedRobDogo',
  measuredRobDogo = 'measuredRobDogo',
  robDogoDiff = 'robDogoDiff',
}

export enum QcSoundingReportListColumnsLabels {
  vesselName = 'Vessel Code',
  vesselCode = 'Vessel Name',
  imoNo = 'IMO No',
  reportId = 'Report ID',
  voyageReference = 'Voyage Reference',
  soundedOn = 'Sounded on',
  soundingReason = 'Sounding Reason',
  computedRobHsfo = 'Computed ROB HSFO',
  measuredRobHsfo = 'Measured ROB HSFO',
  robHsfoDiff = 'ROB HSFO Diff',
  computedRobLsfo = 'Computed ROB HSFO',
  measuredRobLsfo = 'Measured ROB HSFO',
  robLsfoDiff = 'ROB LSFO Diff',
  computedRobDogo = 'Computed ROB DOGO',
  measuredRobDogo = 'Measured ROB LSFO',
  robDogoDiff = 'ROB LSFO Diff',
}
